import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

part 'app_database.g.dart';

@DataClassName('SolicitudLocal')
class Solicitudes extends Table {
  TextColumn get id => text()(); // PK from server OR temporary local ID
  TextColumn get clientId => text().nullable()(); // Link to Outbox
  TextColumn get vehiculoId => text()();
  TextColumn get piezaNombre => text()(); // El nombre del repuesto
  TextColumn get categoriaId => text().nullable()();
  TextColumn get repuestoId => text().nullable()();
  TextColumn get estado => text()();
  TextColumn get descripcion => text().nullable()();
  TextColumn get fotoUrl => text().nullable()();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()(); // Server timestamp
  BoolColumn get synced => boolean().withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {id};
}

// Tablas de caché para metadatos (necesarias para creación offline)
class VehiculosCache extends Table {
  TextColumn get id => text()();
  TextColumn get nombre => text()();
  TextColumn get vin => text()();
  TextColumn get dataJson => text()(); // Datos completos en JSON

  @override
  Set<Column> get primaryKey => {id};
}

class DireccionesCache extends Table {
  TextColumn get id => text()();
  TextColumn get alias => text()();
  TextColumn get detalle => text()();
  TextColumn get dataJson => text()();

  @override
  Set<Column> get primaryKey => {id};
}

class CategoriasCache extends Table {
  TextColumn get id => text()();
  TextColumn get nombre => text()();
  TextColumn get slug => text()();
  TextColumn get dataJson => text()();

  @override
  Set<Column> get primaryKey => {id};
}

class PartesCache extends Table {
  TextColumn get id => text()();
  TextColumn get categoriaId => text()();
  TextColumn get nombre => text()();
  TextColumn get dataJson => text()();

  @override
  Set<Column> get primaryKey => {id};
}

class Outbox extends Table {
  TextColumn get clientId => text()(); // UUID generated by client
  TextColumn get entityType => text()(); // 'solicitud'
  TextColumn get operation => text()(); // 'CREATE' | 'UPDATE' | 'DELETE'
  TextColumn get payload => text()(); // JSON payload
  TextColumn get status => text().withDefault(
    const Constant('PENDING'),
  )(); // PENDING | SYNCING | FAILED | DEAD
  IntColumn get attempts => integer().withDefault(const Constant(0))();
  TextColumn get lastError => text().nullable()();
  DateTimeColumn get createdAt => dateTime()();

  @override
  Set<Column> get primaryKey => {clientId};
}

@DriftDatabase(
  tables: [
    Solicitudes,
    Outbox,
    VehiculosCache,
    DireccionesCache,
    CategoriasCache,
    PartesCache,
  ],
)
class AppDatabase extends _$AppDatabase {
  static final AppDatabase _instance = AppDatabase._internal();
  factory AppDatabase() => _instance;
  AppDatabase._internal() : super(_openConnection());

  @override
  int get schemaVersion => 7; // Aumentado a 7

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
      },
      onUpgrade: (Migrator m, int from, int to) async {
        if (from < 2) {
          await m.addColumn(solicitudes, solicitudes.piezaNombre);
        }
        if (from < 3) {
          await m.createTable(vehiculosCache);
          await m.createTable(direccionesCache);
          await m.createTable(categoriasCache);
        } else if (from < 6) {
          try {
            await m.addColumn(categoriasCache, categoriasCache.slug);
          } catch (_) {}
          try {
            await m.addColumn(categoriasCache, categoriasCache.dataJson);
          } catch (_) {}
        }
        if (from < 7) {
          await m.createTable(partesCache);
        }
      },
      beforeOpen: (details) async {
        await customStatement('PRAGMA foreign_keys = ON');
      },
    );
  }
}

QueryExecutor _openConnection() {
  return driftDatabase(name: 'repuestosya_db');
}
