import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter/foundation.dart' show visibleForTesting;

part 'app_database.g.dart';

@DataClassName('SolicitudLocal')
class Solicitudes extends Table {
  TextColumn get id => text()(); // PK from server OR temporary local ID
  TextColumn get clientId => text().nullable()(); // Link to Outbox
  TextColumn get vehiculoId => text()();
  TextColumn get piezaNombre => text()(); // El nombre del repuesto
  TextColumn get categoriaId => text().nullable()();
  TextColumn get repuestoId => text().nullable()();
  TextColumn get estado => text()();
  TextColumn get descripcion => text().nullable()();
  TextColumn get fotoUrl => text().nullable()();
  // Coordenadas de entrega persistidas en columnas dedicadas (además del
  // JSON del payload del Outbox): permiten leer la ubicación de una
  // solicitud pendiente sin parsear el payload. locationSource: 'gps'|'manual'.
  RealColumn get latitude => real().nullable()();
  RealColumn get longitude => real().nullable()();
  TextColumn get locationSource => text().nullable()();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()(); // Server timestamp
  BoolColumn get synced => boolean().withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {id};
}

// Tablas de caché para metadatos (necesarias para creación offline)
class VehiculosCache extends Table {
  TextColumn get id => text()();
  TextColumn get nombre => text()();
  TextColumn get vin => text()();
  TextColumn get dataJson => text()(); // Datos completos en JSON

  @override
  Set<Column> get primaryKey => {id};
}

class DireccionesCache extends Table {
  TextColumn get id => text()();
  TextColumn get alias => text()();
  TextColumn get detalle => text()();
  TextColumn get dataJson => text()();

  @override
  Set<Column> get primaryKey => {id};
}

class CategoriasCache extends Table {
  TextColumn get id => text()();
  TextColumn get nombre => text()();
  TextColumn get slug => text()();
  TextColumn get dataJson => text()();

  @override
  Set<Column> get primaryKey => {id};
}

class PartesCache extends Table {
  TextColumn get id => text()();
  TextColumn get categoriaId => text()();
  TextColumn get nombre => text()();
  TextColumn get dataJson => text()();

  @override
  Set<Column> get primaryKey => {id};
}

class PerfilAlmacenCache extends Table {
  TextColumn get id => text()();
  TextColumn get nombreComercial => text()();
  TextColumn get verificationStatus => text()();
  TextColumn get dataJson => text()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}

class Outbox extends Table {
  TextColumn get clientId => text()(); // UUID generated by client
  TextColumn get entityType => text()(); // 'solicitud' | 'cotizacion'
  TextColumn get operation => text()(); // 'CREATE' | 'UPDATE' | 'DELETE'
  TextColumn get payload => text()(); // JSON payload
  TextColumn get status => text().withDefault(
    const Constant('PENDING'),
  )(); // PENDING | SYNCING | FAILED | DEAD
  IntColumn get attempts => integer().withDefault(const Constant(0))();
  TextColumn get lastError => text().nullable()();
  DateTimeColumn get createdAt => dateTime()();

  /// UUID v4 de idempotencia, generado UNA vez al encolar (no al reintentar).
  /// Se envía al backend en POST /requests y POST /quotations para que un
  /// reintento post-crash no duplique el registro remoto (brecha B10).
  TextColumn get idempotencyKey => text().nullable()();

  @override
  Set<Column> get primaryKey => {clientId};
}

/// Cotizaciones pendientes de sincronización (creadas offline). Espejo local
/// del patrón de Solicitudes: fila + entrada de Outbox se guardan en la misma
/// transacción Drift.
@DataClassName('CotizacionPendiente')
class CotizacionesPendientes extends Table {
  TextColumn get id => text()(); // PK: ID temporal del cliente (clientId)
  TextColumn get clientId => text().nullable()(); // Link a Outbox
  TextColumn get solicitudId => text()();
  TextColumn get almacenId => text()();
  RealColumn get precio => real()();
  TextColumn get condicion => text().nullable()();
  TextColumn get fotoUrl => text().nullable()(); // file:// local o URL remota
  TextColumn get notas => text().nullable()();
  TextColumn get tiempoEntrega => text()();
  TextColumn get estado => text().withDefault(const Constant('pendiente'))();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();
  BoolColumn get synced => boolean().withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {id};
}

@DriftDatabase(
  tables: [
    Solicitudes,
    Outbox,
    CotizacionesPendientes,
    VehiculosCache,
    DireccionesCache,
    CategoriasCache,
    PartesCache,
    PerfilAlmacenCache,
  ],
)
class AppDatabase extends _$AppDatabase {
  static final AppDatabase _instance = AppDatabase._internal();
  factory AppDatabase() => _instance;
  AppDatabase._internal() : super(_openConnection());

  /// Conexión inyectable para tests (Fase 4 de docs/TESTING.md): permite
  /// usar `NativeDatabase.memory()` sin plugins ni archivos reales.
  @visibleForTesting
  AppDatabase.forTesting(super.executor);

  @override
  int get schemaVersion => 10; // v10: columnas de coordenadas en Solicitudes

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
      },
      onUpgrade: (Migrator m, int from, int to) async {
        if (from < 2) {
          await m.addColumn(solicitudes, solicitudes.piezaNombre);
        }
        if (from < 3) {
          await m.createTable(vehiculosCache);
          await m.createTable(direccionesCache);
          await m.createTable(categoriasCache);
        } else if (from < 6) {
          try {
            await m.addColumn(categoriasCache, categoriasCache.slug);
          } catch (_) {}
          try {
            await m.addColumn(categoriasCache, categoriasCache.dataJson);
          } catch (_) {}
        }
        if (from < 7) {
          await m.createTable(partesCache);
        }
        if (from < 8) {
          await m.createTable(perfilAlmacenCache);
        }
        if (from < 9) {
          await m.addColumn(outbox, outbox.idempotencyKey);
          await m.createTable(cotizacionesPendientes);
        }
        if (from < 10) {
          await m.addColumn(solicitudes, solicitudes.latitude);
          await m.addColumn(solicitudes, solicitudes.longitude);
          await m.addColumn(solicitudes, solicitudes.locationSource);
        }
      },
      beforeOpen: (details) async {
        await customStatement('PRAGMA foreign_keys = ON');
      },
    );
  }
}

QueryExecutor _openConnection() {
  return driftDatabase(name: 'repuestosya_db');
}
